#include "wgui/wibase.h"
#include "wgui/wihandle.h"
#include "materialmanager.h"
#include "cmaterialmanager.h"
#include <unordered_map>
#include <algorithm>
#include <string>
#include "wgui/wiincludes.h"
#include <algorithm>
#include <deque>