name: Build Linux
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: environment-lin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
            name: "Ubuntu GCC-11"
            artifact: "ubuntu_gcc.7z"
            build_type: "RelWithDebInfo"
            cc: "clang-14"
            cxx: "clang++-14"
            archiver: "7z a"
            generators: "Unix Makefiles"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - name: Setup
        id: setup
        uses: Silverlan/common_actions/setup@main
          
      - name: Download binaries
        uses: Silverlan/common_actions/download_build_binaries@main
        continue-on-error: true
          
      - name: Build
        id: build
        uses: Silverlan/wgui/github_actions/build@master
        with:
          repo-directory: '.'

      - name: Create Release Files
        shell: bash
        run: |
          mkdir release
          mkdir release/lib
          rsync build/${{ matrix.config.build_type }}/libwgui.so release/lib/libwgui.so
          rsync build/external_libs/iglfw/libiglfw.so release/lib/libiglfw.so
          rsync build/external_libs/sharedutils/libsharedutils.so release/lib/libsharedutils.so
          rsync build/external_libs/util_image/libutil_image.so release/lib/libutil_image.so
          rsync build/external_libs/vfilesystem/libvfilesystem.so release/lib/libvfilesystem.so
          rsync build/external_libs/mathutil/libmathutil.so release/lib/libmathutil.so
          rsync build/external_libs/datasystem/libdatasystem.so release/lib/libdatasystem.so
          rsync build/external_libs/prosper/libprosper.so release/lib/libprosper.so
          rsync build/external_libs/materialsystem/libmaterialsystem.so release/lib/libmaterialsystem.so
          rsync build/external_libs/materialsystem/libcmaterialsystem.so release/lib/libcmaterialsystem.so
          rsync build/third_party_libs/zlib/libz.so release/lib/libz.so
          rsync build/third_party_libs/glfw/src/libglfw.so release/lib/libglfw.so
          rsync build/third_party_libs/libpng/libpng16.so release/lib/libpng16.so
          rsync build/third_party_libs/libpng/libpng.so release/lib/libpng.so
          rsync build/third_party_libs/VTFLib/src/libVTFLib13.so release/lib/libVTFLib13.so
          rsync build/libwgui.so release/lib/libwgui.so

      - name: Release Binaries
        uses: Silverlan/common_actions/release_nightly_binaries@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}
